server:
  port: 8085

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3314/db_order
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379