services:
  mysql-auth:
    image: mysql:8.0
    container_name: mysql-auth
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_auth
    ports:
      - "3310:3306"

  mysql-user:
    image: mysql:8.0
    container_name: mysql-user
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_user
    ports:
      - "3311:3306"

  mysql-product:
    image: mysql:8.0
    container_name: mysql-product
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_product
    ports:
      - "3312:3306"

  mysql-store:
    image: mysql:8.0
    container_name: mysql-store
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_store
    ports:
      - "3313:3306"

  mysql-order:
    image: mysql:8.0
    container_name: mysql-order
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_order
    ports:
      - "3314:3306"

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"